Microverse Capstone Project
rahimialijan/Microverse-Capstone1-Project pull request #1
Opened 2023-04-26 11:16 UTC by rahimialijan

# Microverse Capstone Project (Desktop and Mobile Version)
1-This is a fully responsive website
2-For building this website HTML, CSS and JavaScript are used.
3-Add linter setup for the project
4-Add a description README file

2023-04-26 12:12 UTC, Olamarx requested changes
Hi @rahimialijan, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Linters passed ✔️ 
- Readme file professional ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 12:12 UTC, Olamarx commented on README.md
> +- [Video Demo Link]()
- [x] There is no link to your video demo, kindly add it.

2023-04-26 12:12 UTC, Olamarx commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [x] It is important to note that to use the Cindy's design, you have to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). Kindly do this to avoid tortuous liability.

2023-04-26 12:12 UTC, Olamarx commented on index.html
> +            </div>
- [ ] You will notice that the hamburger has a transparent background. Kindly adapt it in yours also.

### Your design
![image](https://user-images.githubusercontent.com/86200356/234564183-d9bfe82a-3474-4bd2-936e-3ef63d4549c7.png)

### Behance design
![image](https://user-images.githubusercontent.com/86200356/234563851-7ed92e46-c683-4951-ab3e-2c2c0e700295.png)

2023-04-26 12:12 UTC, Olamarx commented on index.html
> +    </header>
- [ ] While the content of the page is to be personalized, the design should still look very much like that of Cindy, in this case, the top bar is to be divided into a top dark bar and a bottom white bar. The top short bar section should have social media links, logout, and language links aligned to the right. The taller bottom bar with a logo and a list of page links.
The top bar contains a logo to the left. but in all, the top dark bar is missing, kindly add it.

### Your design
![image](https://user-images.githubusercontent.com/86200356/234565609-4be54253-8c57-4e5c-a81a-c60b7f50d9e0.png)

### Behance design
![image](https://user-images.githubusercontent.com/86200356/234565554-a03bfa84-a972-4bc2-b51a-14444377122e.png)

2023-04-26 12:12 UTC, Olamarx commented on index.html
> +    </section>
- [ ] You will notice that the aspect I mark in yellow has a border which makes it look like it is in a box but yours does not, also, the text of the one I marked in green is quite bigger that yours.

### Your design
![image](https://user-images.githubusercontent.com/86200356/234567021-5e75600c-968f-45d5-91b7-df114f9e6c7b.png)

### Behance design
![image](https://user-images.githubusercontent.com/86200356/234566961-683fed80-14e3-4cce-916c-c2a400cf1364.png)

2023-04-26 12:12 UTC, Olamarx commented on index.html
> +        <div class="feature-container">
- [ ] Kindly note that under this h2 text, the line red is not used as an underline, it is a divider and not as wide as that.

### Your design
![image](https://user-images.githubusercontent.com/86200356/234567569-a1d1dc17-a110-491c-b8b2-c5048fea84cc.png)

### Behance design
![image](https://user-images.githubusercontent.com/86200356/234567624-c24ea1fc-a573-4d61-ae4f-f00b0a164f72.png)

2023-04-26 12:12 UTC, Olamarx commented on index.html
> +        <div class="program-card-container">
- [ ] You will notice there is space between these two containers in the mobile version, kindly apply it to yours too.
- [ ] You will notice how organized the description of each card is, kindly apply it to yours also.

### Your design
![image](https://user-images.githubusercontent.com/86200356/234568859-555725ac-ef07-47db-993a-ec270a147b63.png)

### Behance design
![image](https://user-images.githubusercontent.com/86200356/234568661-ac0120dc-d203-4639-89af-4a6be67b2743.png)

2023-04-26 12:12 UTC, Olamarx commented on about.html
> +            <img class="partner" src="images/naver.png" alt="">
- [ ] I can see that some of your img tags do not have alt attribute, I would implore you to add it so that other devices can access your site.

2023-04-26 12:12 UTC, Olamarx commented on styles.css
> +@media (max-width: 768px) {
- [OPTIONAL] You don't need to have this in the media query as it will run from the top of the file and you can adjust the styles in a query down the file which you did for min-width.

2023-04-26 12:46 UTC, rahimialijan commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Hi @Olamarx ,
Thanks for your review I fixed these issues

2023-04-26 18:02 UTC, rahimialijan commented on styles.css
> +@media (max-width: 768px) {
Dear @Olamarx,
Thanks for your review, I really appreciate you. You have really pointed out important points, I just noticed them. I fixed all these problems, thank you for reminding me

2023-04-26 19:40 UTC, Zuhaib042 requested changes
Hi @rahimialijan 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

 ## Highlights
✅ Implemented most of the suggested changes
✅ Linters passing

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 19:40 UTC, Zuhaib042 commented on index.html
> +            <h1 class="big-title">APDT CHANGES PROJECT DELIVERY<br id="break"> EXPERIENCE</h1>
- [ ] Kindly consider increasing the font-size of this main heading as suggested by the previous reviewer to make it identical to the behance design.
your design
![q](https://user-images.githubusercontent.com/96683843/234679354-ba3e6208-5d03-45ea-9d3b-9d9e8f82e0ba.jpg)

Original design
![w](https://user-images.githubusercontent.com/96683843/234679343-cf11f04a-bfc3-4431-a9ae-75bff2f25479.jpg)

2023-04-26 19:40 UTC, Zuhaib042 commented on index.html
> +            aliquid optio quam,</p>
- [ ] Kindly consider removing the `padding-left` from this element to align it to the elements in the top and bottom as you can see in the original design.
- [ ] Also kindly consider adding a `margin-bottom` to this element to have some space between this element and the element below it to make it identical to the original design. 
- [ ] I am asking for these two changes although they were not demanded by the previous reviewer, the reason is that when you added the border to this element, the differences in your design and the original design appears that were not there before.
your design
![q](https://user-images.githubusercontent.com/96683843/234680343-c5bb1244-b9f2-4069-8c5c-503219620b33.jpg)

Behance design
![w](https://user-images.githubusercontent.com/96683843/234680331-cc4d4ecb-7451-45a6-ae76-360090b37591.jpg)

2023-04-26 19:40 UTC, Zuhaib042 commented on index.html
> +        <div class="feature-container">
- [ ] This issue has not been fixed, kindly consider fixing this. as mentioned by the previous reviewer that this is not an underline but a divider and not as wide as that.
![t](https://user-images.githubusercontent.com/96683843/234681286-2cf332c9-1172-46db-b59e-622543061e35.jpg)

2023-04-26 19:40 UTC, Zuhaib042 commented on styles.css
> +    margin-top: 25px;
- [OPTIONAL] Kindly consider adding margin-bottom to this button as there is no space between the button and the border of the parent section at some mobile screen sizes. while in the original design, there is enough space and margin top and bottom to this button.
your design
![a](https://user-images.githubusercontent.com/96683843/234682359-9963ce7b-c606-4e0e-ae83-5b42ffc3f056.jpg)

2023-04-26 19:40 UTC, Zuhaib042 commented on styles.css
> +  --base-color: #d3d3d3;
- [OPTIONAL] The color that you are using in the about page hero section is `#f7f7f7`. the color you are using is stronger, so kindly consider replacing it to make it identical.

2023-04-26 19:40 UTC, Zuhaib042 commented on styles.css
> +    background-color: var(--base-color);
- [OPTIONAL] Here the color in the original design is `#f2f2f2`. kindly consider replacing the background-color of footer  to make it identical to the original design.

2023-04-26 19:40 UTC, Zuhaib042 commented on styles.css
> +    background-color: var(--base-color);
- [OPTIONAL] Here is the background color of this `more` button in the original design `white`. while the color you are using is much stronger and different. kindly consider changing it to make it identical to the original design which is a project requirement.
![g](https://user-images.githubusercontent.com/96683843/234684615-4ce434fd-6a37-47be-92e0-1439c0bc3a5f.jpg)

2023-04-27 09:12 UTC, danmainah requested changes
Hi @rahimialijan , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 09:12 UTC, danmainah commented on index.html
> +            aliquid optio quam,</p>
- [ ] @rahimialijan great work implementing the changes requested however this section has no margin at the bottom as previously requested, I would request you add a margin top and bottom to this paragraph and remove the margin-bottom you added in `h1`
![image](https://user-images.githubusercontent.com/61408860/234815350-0bbde86e-3e55-4bdb-92a9-960e828064b2.png)

2023-04-27 09:41 UTC, rahimialijan commented on index.html
> +            aliquid optio quam,</p>
Hi @danmainah ,
I made the requested changes, thanks to your comments

2023-04-27 10:07 UTC, cynthiainga approved these changes
Hi @rahimialijan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Good design ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct GitHub flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 11:31 UTC, merged